/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Nobuk.GUI;

import Nobuk.Core_System.*;
import Nobuk.DB_Mysql.Mysql_ConnectionFactory;
import Nobuk.DB_Mysql.Mysql_Operations;
import Nobuk.DB_Mysql.Mysql_OperationsI;
import javafx.scene.control.Tab;

import javax.naming.OperationNotSupportedException;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Nobuk
 */
public class Main_Nobuk_GUI extends javax.swing.JFrame {

     private Base_core operations_DB = new Core();
    private final float NumVersion = 0.1f;

    /**
     * Creates new form Main_Nobuk_GUI
     */
    public Main_Nobuk_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnDeletar = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnQuantidadeAdicionar = new javax.swing.JButton();
        btnQuantidadeRemover = new javax.swing.JButton();
        txtSpinnerQuantidade = new javax.swing.JSpinner();
        txtQuantidade = new javax.swing.JSpinner();
        txtNome = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaProdutos = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        MenuSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuSobre = new javax.swing.JMenuItem();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Propriedades"));

        jLabel1.setText("Código:");

        jLabel2.setText("Nome:");

        jLabel3.setText("Quantidade:");

        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Quantidade"));

        btnQuantidadeAdicionar.setText("Adicionar");
        btnQuantidadeAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuantidadeAdicionarActionPerformed(evt);
            }
        });

        btnQuantidadeRemover.setText("Remover");
        btnQuantidadeRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuantidadeRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSpinnerQuantidade)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnQuantidadeRemover)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnQuantidadeAdicionar)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSpinnerQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQuantidadeAdicionar)
                    .addComponent(btnQuantidadeRemover))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQuantidade)
                            .addComponent(txtNome)
                            .addComponent(txtCodigo)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(btnAtualizar)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdicionar)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeletar)
                    .addComponent(btnAdicionar)
                    .addComponent(btnAtualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        TabelaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaProdutos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jMenu1.setText("Arquivo");
        jMenu1.add(jSeparator1);

        jMenuItem1.setText("Salvar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Carregar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator2);

        MenuSair.setText("Sair");
        MenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSairActionPerformed(evt);
            }
        });
        jMenu1.add(MenuSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ajuda");

        MenuSobre.setText("Sobre");
        MenuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSobreActionPerformed(evt);
            }
        });
        jMenu2.add(MenuSobre);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private Object getCodeProductSelecioned(int row)
    {
        if(row != (-1)) return TabelaProdutos.getValueAt(row, 0);
        return 0;
    }

     private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        //Cria um modelo de tabela para poder inserir nela
        DefaultTableModel dtm = (DefaultTableModel) TabelaProdutos.getModel();

        //Pega valores da caixa para add
        Object[] dados = {Integer.parseInt(txtCodigo.getText()), txtNome.getText(), txtQuantidade.getValue()};

        boolean s = operations_DB.add_product(Integer.parseInt(txtCodigo.getText()), txtNome.getText(), (Integer)txtQuantidade.getValue());

        //Se der certo para adicionar então add no banco de dados e na tabela GUI
        if ( s ) {
            //Adicionar o obj na tabela
            dtm.addRow(dados);
            JOptionPane.showMessageDialog(null, "Sucesso.");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Erro.");
        }

    }//GEN-LAST:event_btnAdicionarActionPerformed

     private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed

         //Metodo para poder pegar um item selecionado na tabela (Nunhum = -1)
         int linhaSelecionada = TabelaProdutos.getSelectedRow();

         Object objC = getCodeProductSelecioned(linhaSelecionada);
         //Recuperar codigo do item selecionado na tabela;
         int codigo = (Integer) objC;

         Mysql_OperationsI mysqlOp = new Mysql_Operations();
         Product p = mysqlOp.SQL_getProductByCode( codigo ); //Get product by code

         if (linhaSelecionada != (-1)) {
             int cod = Integer.parseInt(txtCodigo.getText());
             String nome = txtNome.getText();
             int quantity = (Integer) txtQuantidade.getValue();

             TabelaProdutos.setValueAt(cod, linhaSelecionada, 0);
             TabelaProdutos.setValueAt(nome, linhaSelecionada, 1);
             TabelaProdutos.setValueAt(quantity, linhaSelecionada, 2);

             operations_DB.att_product(p.getId(), cod, nome, quantity);

             JOptionPane.showMessageDialog(null, "Sucesso.");
         }
         else JOptionPane.showMessageDialog(null, "Falha ao atualizar produto.");

     }//GEN-LAST:event_btnAtualizarActionPerformed



    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        //Cria um modelo de tabela para poder remover um item.
        DefaultTableModel dtm = (DefaultTableModel) TabelaProdutos.getModel();

        //Metodo para poder pegar um item selecionado na tabela (Nunhum = -1)
        int itemSelectionado = TabelaProdutos.getSelectedRow();

        Object objC = getCodeProductSelecioned(itemSelectionado);
        //Recuperar codigo do item selecionado na tabela;
        int codigo = (Integer) objC;

        Mysql_OperationsI mysqlOp = new Mysql_Operations();

        Product p = mysqlOp.SQL_getProductByCode( codigo ); //Get product by code
        int itemID = p.getId();

        if (itemSelectionado >= 0 && operations_DB.delete_product( itemID ))
        {
            dtm.removeRow( itemSelectionado );
            JOptionPane.showMessageDialog(null, "Produto deletado com Sucesso.");
        }
        else JOptionPane.showMessageDialog(null, "Selecione um produto.");

    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnQuantidadeAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuantidadeAdicionarActionPerformed
        //Metodo para poder pegar um item selecionado na tabela (Nunhum = -1)
        int linhaSelecionada = TabelaProdutos.getSelectedRow();

        Object objC = getCodeProductSelecioned(linhaSelecionada);
        //Recuperar codigo do item selecionado na tabela;
        int codigo = (Integer) objC;

        Mysql_OperationsI mysqlOp = new Mysql_Operations();
        Product p = mysqlOp.SQL_getProductByCode( codigo ); //Get product by code

        if (linhaSelecionada != (-1)) {
            int quantidade = (Integer) txtSpinnerQuantidade.getValue();

            int finalQuantidade = p.getQuantity() + quantidade;

            TabelaProdutos.setValueAt(finalQuantidade, linhaSelecionada, 2);

            operations_DB.add_quantity(p.getId(), quantidade);

            JOptionPane.showMessageDialog(null, "Sucesso.");
        }
        else JOptionPane.showMessageDialog(null, "Falha ao atualizar produto.");

    }//GEN-LAST:event_btnQuantidadeAdicionarActionPerformed

    private void btnQuantidadeRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuantidadeRemoverActionPerformed
        //Metodo para poder pegar um item selecionado na tabela (Nunhum = -1)
        int linhaSelecionada = TabelaProdutos.getSelectedRow();

        Object objC = getCodeProductSelecioned(linhaSelecionada);
        //Recuperar codigo do item selecionado na tabela;
        int codigo = (Integer) objC;

        Mysql_OperationsI mysqlOp = new Mysql_Operations();
        Product p = mysqlOp.SQL_getProductByCode( codigo ); //Get product by code

        if (linhaSelecionada != (-1)) {
            int quantidade = (Integer) txtSpinnerQuantidade.getValue();

            int finalQuantidade = p.getQuantity() - quantidade;

            if(finalQuantidade >= 0) {
                TabelaProdutos.setValueAt(finalQuantidade, linhaSelecionada, 2);

                operations_DB.remove_quantity(p.getId(), quantidade);

                JOptionPane.showMessageDialog(null, "Sucesso.");
            }
            else JOptionPane.showMessageDialog(null, "Erro. Não há quantidade sulficiente para retirar.");
        }
        else JOptionPane.showMessageDialog(null, "Falha ao atualizar produto.");
    }//GEN-LAST:event_btnQuantidadeRemoverActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        //Carregar
        //Cria um modelo de tabela para poder inserir nela
        DefaultTableModel dtm = (DefaultTableModel) TabelaProdutos.getModel();

        //Pega valores da caixa para add
        Object[] dados;

        Mysql_OperationsI db = new Mysql_Operations();
        List<Product> lista = db.SQL_getProducts();

        //Adicionar os obj na tabela
        for(Product p : lista) {
            dados = new Object[]{p.getCode(), p.getName(), p.getQuantity()};
            dtm.addRow(dados);
        }
        JOptionPane.showMessageDialog(null, "Sucesso.");

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void MenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_MenuSairActionPerformed

    private void MenuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSobreActionPerformed
        JOptionPane.showMessageDialog(null, "version - " + NumVersion);
    }//GEN-LAST:event_MenuSobreActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void TabelaProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaProdutosMouseClicked
        int linhaSelecionada = TabelaProdutos.getSelectedRow();
        if(linhaSelecionada != (-1)) {
            txtCodigo.setText( TabelaProdutos.getValueAt(linhaSelecionada, 0).toString() );
            txtNome.setText( TabelaProdutos.getValueAt(linhaSelecionada, 1).toString() );
            txtQuantidade.setValue( TabelaProdutos.getValueAt(linhaSelecionada, 2) );
        }
    }//GEN-LAST:event_TabelaProdutosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Nobuk_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Nobuk_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Nobuk_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Nobuk_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Nobuk_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuSair;
    private javax.swing.JMenuItem MenuSobre;
    private javax.swing.JTable TabelaProdutos;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnQuantidadeAdicionar;
    private javax.swing.JButton btnQuantidadeRemover;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNome;
    private javax.swing.JSpinner txtQuantidade;
    private javax.swing.JSpinner txtSpinnerQuantidade;
    // End of variables declaration//GEN-END:variables
}
